### PR TITLE
WIP for issue 717

### PR DESCRIPTION
**Pull request by rberenguel**
Can’t figure out the problem with several apply/function blocks in the test (test named “multiple”). The other 4 cases considered in tests (not exhaustive yet though) pass. I have left the ONLY flag since this is still WIP

@olafurpg any idea? I have drawn a few ASTs and followed the capture rules from the rewrite on paper and it looks like they should work as I'd like, so I ran out of ideas about how to test it more

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you for this PR @rberenguel! I am personally excited about this rewrite 😄 it may take a few days until I manage to look at this closer, I'm clearing my queue after Scala World

**Comment by rberenguel** [comment]
@olafurpg no rush, I'll give it another try to investigate what might be off ASAP

**Comment by olafurpg** [comment]
Closing due to inactivity. Please reopen if you would like to pick this up again @rberenguel !

**Comment by rberenguel** [comment]
Sorry @olafurpg I had totally forgotten about this. I'll give it another shot (or... try :D )

**Pull request closed without merging**
