### PR TITLE
YML: Make java11 primary, remove java8

### PR DESCRIPTION
**Pull request by kitbellew**

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
LGTM!

**Comment by lefou** [comment]
Nice move. Releasing it as a patch release was not.

**Comment by kitbellew** [comment]
> Nice move. Releasing it as a patch release was not.

@lefou should we release the next version as minor? cc @tgodzik

**Comment by tgodzik** [comment]
That's my bad, we should have released as a minor bump. We should do that for the next one then.

**Comment by lefou** [comment]
> > Nice move. Releasing it as a patch release was not.
> 
> @lefou should we release the next version as minor? cc @tgodzik

It won't hurt. But unless, you plan to roll back this change in the `3.7.x` line, it won't change much for user.

**Pull request merged**
