### PR TITLE
Add end marker after the last token of a tree

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalameta/scalafmt/issues/2559

### CODE REVIEW

**Review by kitbellew — APPROVED** [review]
still, why is the comment part of the `owner`?

**Comment by tgodzik** [comment]
> still, why is the comment part of the `owner`?

From what I checked the positions are correct and the comments is not a part of any of the defs.

Is it possible that `tokenAfter` just gets the next token after the tree? It uses `nextNonComment`, which doesn't iterate over tree tokens anymore.

**Comment by kitbellew** [comment]
@tgodzik we might need a fix in `scalameta` after all. in this code
```
def f(s: String) =
  val t = "Bar"
  val u = "Baz"
  s"$t $u $s"
  // final comment
```
the comment is not part of the body:
```
TYPE: Defn$Def$DefnDefImpl
SOURCE: def f(s: String) =
  val t = "Bar"
  val u = "Baz"
  s"$t $u $s"
STRUCTURE: Defn.Def(Nil, Term.Name("f"), Nil, List(List(Term.Param(Nil, Term.Name("s"), Some(Type.Name("String")), None))), None, Term.Block(List(Defn.Val(Nil, List(Pat.Var(Term.Name("t"))), None, Lit.String("Bar")), Defn.Val(Nil, List(Pat.Var(Term.Name("u"))), None, Lit.String("Baz")), Term.Interpolate(Term.Name("s"), List(Lit.String(""), Lit.String(" "), Lit.String(" "), Lit.String("")), List(Term.Name("t"), Term.Name("u"), Term.Name("s"))))))
TOKENS: def,∙,f,(,s,:,∙,String,),∙,=,¶,∙,∙,val,∙,t,∙,=,∙,"Bar",¶,∙,∙,val,∙,u,∙,=,∙,"Baz",¶,∙,∙,s,",,$,t,,∙,$,u,,∙,$,s,,,"
```
therefore, end marker looks like this:
```
def f(s: String) =
   val t = "Bar"
   val u = "Baz"
   s"$t $u $s"
end f
// final comment
```

**Comment by kitbellew** [comment]
well, and without end marker, same story:
```
def f(s: String) =
   val t = "Bar"
   val u = "Baz"
   s"$t $u $s"
// final comment
```
not sure if we already discussed this, i can't remember.

**Comment by tgodzik** [comment]
So that's kind of expected. Outdent token is inserted before the next non comment token, which means that the comments still belong to the body of the Def.

I will check how it is in Dotty, but I'd don't expect indentation to be influenced by comments

**Comment by tgodzik** [comment]
Ach no, I totally misunderstood what you were saying. But I think we don't really want to have the comment as part of the previous tree. Not sure how we would differentiate:

```scala
def f(s: String) =
   val t = "Bar"
   val u = "Baz"
   s"$t $u $s"
  // final comment

def g = 123
```

from 

```scala
def f(s: String) =
   val t = "Bar"
   val u = "Baz"
   s"$t $u $s"

// comment about g
def g = 123
```

Indentation isn't needed for comments, you can have:
```scala

class A:
  def hello = 1
  def bye = 1
// comment
  def ciao = 2
end A
```
and it still compiles.

I think the current situation is the best we can have.

**Pull request merged**
