### PR TITLE
Add optIn.breaksInsideChains = true

### LINKED ISSUE #988: Completely turn off optIn.breakChainOnFirstMethodDot
- **Version**: 1.0.0-RC4
- **Integration**: neo-sbt-scalafmt
- **Configuration**:
```
maxColumn = 120
continuationIndent.defnSite = 2
align = none
align.openParenCallSite = false
danglingParentheses = true
includeCurlyBraceInSelectChains = false
optIn.breakChainOnFirstMethodDot = true
newlines.penalizeSingleSelectMultiArgList = false
rewrite.rules = [AvoidInfix]

```

## Steps

I ran scalafmt like this:

```bash
sbt scalafmt
```

## Problem

Original code:

```scala
sql"""
  |some sql code here
""".stripMargin
  .map(_.long(1)).single().future()

val termination = httpApi.bindingFuture
  .flatMap(_.unbind())
  .flatMap(_ => actorSystem.terminate())
```

With `optIn.breakChainOnFirstMethodDot = false` scalafmt formats code like this:
```scala
sql"""
  |some sql code here
""".stripMargin.map(_.long(1)).single().future()

val termination = httpApi.bindingFuture.flatMap(_.unbind()).flatMap(_ => actorSystem.terminate())
```

With `optIn.breakChainOnFirstMethodDot = true` scalafmt formats code like this:
```scala
sql"""
  |some sql code here
""".stripMargin
  .map(_.long(1))
  .single()
  .future()

val termination = httpApi.bindingFuture
  .flatMap(_.unbind())
  .flatMap(_ => actorSystem.terminate())
```

## Expectation

I would like to preserve original code for both code fragments. I don't want to generalize rules for dot calls in my codebase.

## Workaround

No workaround at the moment as far as I know.

### PR DESCRIPTION
**Pull request by olafurpg**
This option makes it possible to control line breaks around select
chains. Fixes #988.

Review @xerial @LMnet

### CODE REVIEW

**Comment by xerial** [comment]
Thanks. I'll test this version of scalafmt to re-format https://github.com/wvlet/airframe/.

**Comment by LMnet** [comment]
Thanks for the fix! I'll try to check it in a few days.

**Comment by olafurpg** [comment]
No rush from my side 😄

**Comment by LMnet** [comment]
I tested new option and all works as expected.

Just for clearness - what is the purpose of empty `scalafmt-tests/src/test/resources/optIn/SelectChains` file?

**Comment by olafurpg** [comment]
Good to hear @LMnet I've removed that file, good catch!

**Comment by xerial** [comment]
@olafurpg Tested this version in https://github.com/wvlet/airframe/pull/103 and this option works really well :) 

Could you release this version for sbt 1.0.0 and 0.13.x? Personally I'd like to use 1.0.0 but some sbt plugins are not fully migrated to 1.0.0 yet (e.g., https://github.com/47deg/sbt-microsites/pull/221), so it would be great if it can be used with sbt 0.13.x.

**Comment by olafurpg** [comment]
Good to hear @xerial com:geirsson:sbt-scalafmt doesn't support sbt 0.13 but neo-sbt-scalafmt does https://github.com/lucidsoftware/neo-sbt-scalafmt

I personally use the cli bootstrap script
```scala
wget -L https://github.com/scalameta/scalafmt/raw/master/scalafmt
chmod +x scalafmt
./scalafmt
```
commit it to the git repo and run `./scalafmt` on CI.
http://scalameta.org/scalafmt/#Coursier

**Comment by olafurpg** [comment]
I just set the deadline for the v1.3.0 milestone to Sept 18th, https://github.com/scalameta/scalafmt/milestone/18 releases usually take a while due to the intellij plugin.

**Pull request merged**
