### PR TITLE
FormatOps: handle `if` as if no `else` when `keep`

### LINKED ISSUE #3173: Newline before multi-line can't be "kept" as in source
## Configuration (required) ##
```
version = 3.4.3

runner.dialect = scala212
docstrings.style = keep
maxColumn = 100

newlines.source = keep
newlines.beforeMultiline = keep
# newlines.forceBeforeMultilineAssign = never
```

## Command-line parameters (required) ##

When I run scalafmt via CLI like this: `-c scalafmt.conf test-scalafmt.scala`

## Steps

Given code like this:
```scala
class Foo {
  def foo(): Unit = {
    // foo
    val foo = if (true) {
        ""
      } else {
        "a"
      }
  }
}
```

## Problem

Scalafmt formats code like this:
```scala
class Foo {
  def foo(): Unit = {
    // foo
    val foo =
      if (true) {
        ""
      } else {
        "a"
      }
  }
}
```

## Expectation

I would like the formatted output to look like this (not change the val line):
```scala
class Foo {
  def foo(): Unit = {
    // foo
    val foo = if (true) {
      ""
    } else {
      "a"
    }
  }
}

```

## Workaround

No workaround found after fiddling with settings for several hours :(

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #3173.

### CODE REVIEW

**Comment by iuliand-db** [comment]
Thanks a lot for doing this! for what it's worth, LGTM!

**Comment by iuliand-db** [comment]
Is there anything we could help to get this in? I could test it locally, but I'd prefer to stick to an official pre-release version than to fork this repo.

**Review by tgodzik — APPROVED** [review]
I am off on vacation, but the pr looks good after a quick look!

**Comment by kitbellew** [comment]
> I am off on vacation, but the pr looks good after a quick look!

thank you! where are you vacationing?

**Comment by tgodzik** [comment]
> > I am off on vacation, but the pr looks good after a quick look!
> 
> thank you! where are you vacationing?

Madrid and Barcelona, unfortunately it's much colder than expected 😅

**Pull request merged**
