### PR TITLE
FormatWriter: fix bugs around blank lines in top-level stats

### LINKED ISSUE #2511: Feature request: ability to have multiple blank lines around various kinds of elements
- **Version**: 3.0.0-RC2

## Desire

I should like to be able to configure Scalafmt to format code to look like this, with two blank lines surrounding top-level [template definitions (`TmplDef)`](https://dotty.epfl.ch/docs/reference/syntax.html#declarations-and-definitions):

```scala
import scala.collection.mutable.ArrayBuffer


/** 2 blank lines above and below top-level trait definition */
trait A


// 2 blank lines above top-level class definition
// (none below due to end of file)
class B:

  /** 1 blank line above and below method definition */
  def A = ???

  /** 1 blank line above and below nested trait definition */
  trait Bar
      extends A

  /** 1 blank line above (none below due to end of file) */
  lazy val x = 1
```

Some coding styles may prefer something like this, with three blank lines surrounding top-level template definitions and two blank lines surrounding nested method definitions:

```scala
import scala.collection.mutable.ArrayBuffer



/** 3 blank lines above and below top-level trait definition */
trait A:

   // 1 blank line above (2 below due to following def)
   val x = 32
  
  
   /** 2 blank lines above and below nested method definition */
   def A =
      // beginning of a lengthy method body containing a blank line
     
      // continuation of lengthy body following a blank line
      ???


   // 2 blank lines above nested method definition
   // (3 below due following class)
   def B = ???



// 3 blank lines above top-level class definition
// (none below, due to end of file)
class B:


   /** 2 blank lines above and below */
   def A = ???


   /** 2 blank lines above and below nested-trait */
   trait Bar
      extends A


   // 1 blank line normally above val, but 2 enforced due to
   // preceding nested trait (none following due to end of file)
   lazy val x = 1
```

## Rationale

Being able to add more than one blank line before certain major elements such as [template definitions (`TmplDef)`](https://dotty.epfl.ch/docs/reference/syntax.html#declarations-and-definitions) would make it easier to distinguish between the various major and minor elements in a source file. For example, it is a lot easier to see where a class begins and ends if that class is surrounded by more whitespace than the methods and other items _within_ that class. In Scala, where multiple traits, classes, objects, etc. are often defined in a single source file, marking the boundaries of such major elements clearly would be especially useful.

Similarly, it is not unusual in many Scala coding styles to allow single blank lines within a method body. It would therefore be useful to be able to configure, say, two blank lines before and after method definitions, so that the boundaries of the method are clear and not obfuscated by the the intra-method blank lines.

## Notes

1. This feature would be useful even if it addressed only top-level template definitions.

2. However, it would be beneficial to be able to configure the number of blank lines surrounding many of the different Scala 3 syntax [Declarations and Definitions](https://dotty.epfl.ch/docs/reference/syntax.html#declarations-and-definitions) (e.g. `RefineDcl`, `TmplDef`, `Extension`).

3. It may be useful to be able to configure the minimum number of blank lines surrounding top-level elements of each kind separately from those same elements when they are nested (e.g. within the body of a template or method).

4. It may also be useful to be able to treat single-line declarations and definitions separately from those that extend over several lines.

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #2511.

### CODE REVIEW

**Comment by kitbellew** [comment]
@djneades this should cover all your cases.

**Review by tgodzik — CHANGES_REQUESTED** [review]
Looks good, but the tests seems to be failing.

**Comment by kitbellew** [comment]
> Looks good, but the tests seems to be failing.

yes, the `bug in trailingComment` fix had a bug :)

**Comment by kitbellew** [comment]
@tgodzik bug fixed.

**Review by tgodzik — APPROVED** [review]
LGTM!

**Comment by djneades** [comment]
@kitbellew `3.0.0-RC4+22-19f883af-SNAPSHOT` is looking good to me, thank you.

**Comment by kitbellew** [comment]
@djneades mazal tov!

**Comment by djneades** [comment]
@kitbellew I’ve just tried playing with end markers for the first time, still with `3.0.0-RC4+22-19f883af-SNAPSHOT`. Is it possible to control the number of blank lines around those? I’ve tried using this config:

```
maxColumn = 80

runner.dialect = scala3

newlines {
  topLevelStatementBlankLines = [
      { blanks { before = 3, after = 3 } }
      { regex = "^Import", minBreaks=0, blanks { before = 1, after = 3 } }
      { regex = "^Pkg", minBreaks=0, blanks { before = 0, after = 3 } }
      { regex = "^Defn.Def", blanks { before = 2, after = 2 } }
      {
        regex = "^(Defn.Var|Defn.Val|Defn.Type)"
        blanks { before = 1, after = 1 }
      }
      {
        regex = "^Term.EndMarker", minBreaks=0, blanks { before = 1, after = 1 }
      }
    ]
}
```

I’m not absolutely sure whether I have the `Term.EndMarker` correct, but in any case it is not working for me. This:

```scala
package bug

final class Builder:

  def coalesce(seq: List[String]): Seq[String] =
    ???

end Builder

val ul = Builder()
```

is formatted as this:

```scala
package bug



final class Builder:

  def coalesce(seq: List[String]): Seq[String] =
    ???



end Builder

val ul = Builder()
```

My goal here is to have precisely one blank line above the end marker.

TIA.

**Comment by kitbellew** [comment]
> ```
> newlines {
>   topLevelStatementBlankLines = [
>       { regex = "^Defn.Def", blanks { before = 2, after = 2 } }
>       {
>         regex = "^Term.EndMarker", minBreaks=0, blanks { before = 1, after = 1 }
>       }
>     ]
> }
> ```
> 
> ```scala
>   def coalesce(seq: List[String]): Seq[String] =
>     ???
> 
> end Builder
> ```

the first rule says put 2 blanks after `def`, and the second asks for 1 before `end`. `def` wins, with more blanks.

**Comment by djneades** [comment]
@kitbellew That would make sense. But, with my example, Scalafmt is adding three blank lines above the end marker, not two …

**Comment by djneades** [comment]
@kitbellew Thinking about this a little more, there seems to be a special rule that results in at most one blank line immediately after the beginning of a template (in that there is only one blank line between the `final class Builder` line and the following `def`). I wonder whether there should be a similar rule to limit the blank lines before the end marker?

**Comment by djneades** [comment]
@kitbellew There is also a potential minor issue that end markers inserted with `rewrite.scala3.insertEndMarkerMinLines = 30` have no blank lines above them at all, even with the configuration above.

**Comment by kitbellew** [comment]
> @kitbellew Thinking about this a little more, there seems to be a special rule that results in at most one blank line immediately after the beginning of a template (in that there is only one blank line between the `final class Builder` line and the following `def`). I wonder whether there should be a similar rule to limit the blank lines before the end marker?

first, the end markers are explicitly skipped and never match these rules (i wrote it but forgot).

second, the reason they behave like this is because the way the parser produces them is, they are a completely separate statement following the one they are ending. so the previous gets its blanks, before the end marker is even found. i can fix this, by moving the blanks to after the end marker.

however, what i still can't fix -- and about to give up on, because i also have a day job -- is actually controlling blanks before the end marker. (and this has to do with the rewrite.) so far, i can hardcode no-blanks before any end markers.

**Comment by djneades** [comment]
@kitbellew Thank you. I absolutely understand about the day job and I am grateful for all your work.

**Pull request merged**
