### PR TITLE
Scalameta: upgrade to v4.4.23

### PR DESCRIPTION
**Pull request by kitbellew**

### CODE REVIEW

**Comment by kitbellew** [comment]
@tgodzik is it time to release v3.0.0 (no RC)? or is there still something in the pipeline?

**Comment by tgodzik** [comment]
I still need to take a look at the Dotty tests to see if we can find more issues we need to fix in the parser. But those should be minor things, so probably nothing blocking. Let me try to fix those until end of the week and then do the release?

**Comment by kitbellew** [comment]
no rush, if you're still looking. we can merge this commit (review, please) and go with rc6 for now.

**Review by tgodzik — APPROVED** [review]
LGTM!

**Comment by tgodzik** [comment]
Also, I looked through the issues and I see around 10 bugs, but need to investigate them further.

**Comment by kitbellew** [comment]
> Also, I looked through the issues and I see around 10 bugs, but need to investigate them further.

that's in scalameta, right?

**Comment by tgodzik** [comment]
> > Also, I looked through the issues and I see around 10 bugs, but need to investigate them further.
> 
> that's in scalameta, right?

Yeah, but I don't see anything major, so should be quick (hopefully)

**Pull request merged**
