### PR TITLE
Fix #472, Blank lines removed too aggresively in sbt files

### LINKED ISSUE #472: Blank lines removed too aggresively in sbt files
When defining build files, I usually separate out the various settings into different groups using newlines and comments... but scalafmt is stripping them out.  (My example is contrived I don't literally break it out line by line like that)
- **Version**: 0.4.1
- **Integration**: sbt
- **Configuration**: happens in default
#### Starting

``` scala
lazy val test = (project in file("test"))
  .settings(
    // Name
    name := "test",

    // Version
    version := "1.0.0",

    // Blah
    scalaVersion := "2.11.8"
  )
```
#### Scalafmt

``` scala
lazy val test = (project in file("test")).settings(
  // Name
  name := "test",
  // Version
  version := "1.0.0",
  // Blah
  scalaVersion := "2.11.8"
)
```
#### Wanted

``` scala
lazy val test = (project in file("test"))
  .settings(
    // Name
    name := "test",

    // Version
    version := "1.0.0",

    // Blah
    scalaVersion := "2.11.8"
  )
```

### PR DESCRIPTION
**Pull request by AnamikaD**
Test Case for the Fix #472 passes, but 152 failed test cases

### CODE REVIEW

**Comment by AnamikaD** [comment]
@olafurpg please review this :)

**Comment by AnamikaD** [comment]
I have added the flag and test case. What is the functionality of OneArgOneLineSplit?

**Comment by olafurpg** [comment]
Have you pushed your new changes?

**Comment by olafurpg** [comment]
@AnamikaD Please reopen this PR if you want to take another stab at this issue :) I'm gonna close this PR to clean up the PR queue.

**Pull request closed without merging**
