### PR TITLE
Router: handle if with/without braces consistently

### LINKED ISSUE #1747: Inconsistent formatting of if/else
Version: 2.4.2

```
val a = 5

// 1
val ok1 = if (a > 10) Some(a) else None

// 2
val ok2 = if (a > 10) {
  Some(a)
} else {
  None
}

// 3
val ok3 = if (a > 10)
  Some(a)
else
  None

// 4
val ok4 = if (a > 10) Some(a) else {
  None
}

// examples 1-2 are unaffected

// example 3 is re-written as:
val ko3 =
  if (a > 10)
    Some(a)
  else
    None

// example 4 is re-written as:
val ko4 =
  if (a > 10) Some(a)
  else {
    None
  }

```

It seems that the formatting of examples 3 and 4 is not consistent with example 2; The "if" is pushed to the next line for some reason.

### PR DESCRIPTION
**Pull request by kitbellew**
To do that, allow space only if 'else' is empty or the entire expression fits on the line.

Fixes #1747.

`scala-repos` diffs: https://github.com/kitbellew/scala-repos/commit/3670a380d2efa282b8432c8f1ab45ca49efa2991?w=1

p.s. old diffs: https://github.com/kitbellew/scala-repos/commit/dc650f97f6666e1120da601e2c98ad2233d86c96?w=1

### CODE REVIEW

**Comment by kitbellew** [comment]
@olafurpg @tanishiking @poslegm PTAL

**Comment by kitbellew** [comment]
> Thank you, I like it! But I would rather wait for the rest maintainers opinion because of large diffs in scala-repos

@olafurpg @tanishiking your thoughts on this change? the diffs in `scala-repos` change
```
  val a = if (b) {
    c
  } else d
```
to
```
  val a =
    if (b) {
      c
    } else d
```
for consistency with existing
```
  val a =
    if (b)
      c
    else d
```

**Comment by tanishiking** [comment]
Thanks! I'll take a look this evening :)

**Comment by kitbellew** [comment]
@tanishiking @poslegm PTAL, updated code with Rikito's suggestion, uploaded new diffs (mostly whitespace for indent, and some non-brace `if`s looking more like brace `if`s).

**Comment by poslegm** [comment]
I don't sure that additional indent is the best solution for the consistency problem. 

Especially I don't like this:
```scala
val x = if (x > max) "a"
  else "b"
```

Personally I prefer first version of @kitbellew's changes because it perfectly standardizes if/else formatting. But because of large diff in real-world codebases we may be forced to keep current "liberal" behavior 😞

**Comment by kitbellew** [comment]
> Especially I don't like this:
> 
> ```scala
> val x = if (x > max) "a"
>   else "b"
> ```

Neither do I (including the brace version). Continuing without a break logically means that there's only one expression on the right, which works with a `def` returning a `Unit`, a `match`, or a `case` guard; but it reads poorly in assignment which requires both `then` and `else` (i.e., two expressions).

Abandon? Add a parameter similar to `newlines.alwaysBeforeMultilineDef` or `alwaysBeforeElseAfterCurlyIf`, whichever one looks more appropriate? Generally, I was planning to handle such cases in my #1627 which I will start submitting soon anyway.

**Comment by poslegm** [comment]
It really looks like a good case for `newlines.*` configuration. I am ok with new setting for this.

**Comment by kitbellew** [comment]
> It really looks like a good case for `newlines.*` configuration. I am ok with new setting for this.

should we simply reuse `alwaysBeforeMultilineDef` with an edition guard? this setting seems quite similar in nature, especially if we interpret `Def` as `Defn` (which covers `val`, `var` etc.). we've done it before with `alwaysBeforeElseAfterCurlyIf` as applied to `try-finally`.

**Comment by poslegm** [comment]
> should we simply reuse alwaysBeforeMultilineDef with an edition guard?
sounds reasonable

**Comment by paulkore** [comment]
Hi all, I'm glad to see that progress is being made on this issue!

@tanishiking , to answer your question from before, I agree with you: 
Placing the "if" on the same line as the val assignment seems to be standard practice in languages where "if/else" has a return value.

However, I'm not sure about the indentation. 
Based on the codebases that I've worked in, it seems more popular to keep the same indentation in if/else, regardless of whether it's used procedurally or in an assignment:

```
// procedural
if (a > 10) {
  println("A")
} else {
  println("B")
}

// assignment
val x = if (a > 10) {
  Some(a)
} else {
  None
}
```

**Comment by tanishiking** [comment]
Thank you so much for modifying @kitbellew and your comment @paulkore 

IMO, I think we don't have to fix this "inconsistency" between if/else with and without braces. (I mean it's best to maintain the status quo).

Though @paulkore mentioned that there's an inconsistency between those formatting results, I think we don't have to honor the consistency about the indent/newline between them, because (as far as I know) a lot of scala developers usually use different indentation/newline styles for if/else statement with and without braces.

```scala
// without braces
val ok3 =
  if (a > 10) Some(a)
  else None

// with braces
val ok3 = if (a > 10) {
  Some(a)
} else {
  None
}
```

That's why I believe it's better not to change the current behavior.
It might be better to hear more opinions from other scala developers, I guess.

---

It's ok with adding an option but in that case, I think it's better to keep the default behavior.

**Pull request closed without merging**
