### PR TITLE
Make comment blocks line up.

### PR DESCRIPTION
**Pull request by adampauls**
Partial fix for #1484. I don't know this code all that well so I'm not sure if there are other cases worth testing. Thanks!

UPDATE: I think I fixed the rest of #1484. Please take another look if this isn't your first time.

### CODE REVIEW

**Comment by adampauls** [comment]
cc @droptheplot

**Comment by adampauls** [comment]
Friendly ping @tanishiking. It would be nice to have an RC2 with this bug fix soon!

**Comment by tanishiking** [comment]
Thank you for working on this :) I'll look at this tomorrow.

**Comment by adampauls** [comment]
I agree, that seems much more robust, although I don’t know the code well enough to make that change on my own. I can take a shot if that’s the only way this change will get made though!

**Comment by adampauls** [comment]
Also, IMHO it seems a little weird to leave the broken implementation in place. Seems like you could merge this fix and refactor later (with now-passing tests to help catch problems!), or you could revert #1470. Blocking this fix on doing it the right way feels a bit let like letting perfect be the enemy of the good?

**Comment by tanishiking** [comment]
I think what we need to do to fix it is
- delete [Split#adapt](https://github.com/scalameta/scalafmt/blob/741406c482ace0faedd78d359f052f5885c3aeb3/scalafmt-core/shared/src/main/scala/org/scalafmt/internal/Split.scala#L37-L41)
- revert https://github.com/scalameta/scalafmt/pull/1470

It would be helpful if you work on that, but if you don't have time for working on that, I'm willing to implement it instead (maybe this weekend) :)
Though I really appreciate your effort, I can't merge this PR as it is, sorry.

**Comment by droptheplot** [comment]
@adampauls 
Thanks for pointing out missing cases!

@tanishiking 
While deleting `adapt` and reverting previous commit works for current test case, it doesn't work for many others and will fail 9 other tests (including that [feature](https://github.com/scalameta/scalafmt/blob/741406c482ace0faedd78d359f052f5885c3aeb3/scalafmt-tests/src/test/resources/unit/Comment.stat#L68-L79)). Probably `adapt` should stay?

**Comment by tanishiking** [comment]
Thank you for your comment!
Yeah, that's the point. 

Personally, I feel these changes(add indents for line comments in method chains) have a sense of inconsistency as to the position of line comments.

If we keep the adapt method and keep the line comments stay at the beginning of lines, I think scalafmt should keep **all** line comments left without any exceptions.
If we add an indentation for line comments, I think scalafmt should treat all line comments in the same way. For pursuing a simplicity and consistency.

That's why I personally think we probably should

- Just revert the previous commit
- Remove adapt method and add indents for all line comments
  - it will drop the feature which keep line comments at the first column and break some of existing tests, but I think all of them related to the feature.
  - I think it's inevitable for keeping indentation for line comments, without a bit of invoncistency.
  - Since there could be an unpected regression for deleting adapt method, we need a thorough investigation before carrying out this plan (if we gonna follow this plan, maybe we should merge this PR for now because, as @adampauls said, it could take some time)

What do you think about this?

**Comment by tanishiking** [comment]
Though I have some concerns about this, as @adampauls said, maybe it would be better to merge this for now. About `adapt` method, I'll raise another ticket.
Anyway, thank you very much for these contributions @adampauls @droptheplot ! This PRs kicked us off to fix the problems.

**Pull request merged**
