### PR TITLE
Scalameta: upgrade to v4.4.27

### PR DESCRIPTION
**Pull request by kitbellew**

### CODE REVIEW

**Comment by tgodzik** [comment]
We could try updating to scalameta SNAPSHOT first next time to figure out if anything needs to be fixed still. We wouldn't need to do a rerelease then.

**Comment by kitbellew** [comment]
> We could try updating to scalameta SNAPSHOT first next time to figure out if anything needs to be fixed still. We wouldn't need to do a rerelease then.

1. where do we get a scalameta snapshot?
2. should we somehow include testing of scalafmt before merging scalameta commits? a bit drastic but it looks like scalafmt has more unit tests (and out of more than 3.5k tests, only two failed, so...)

**Comment by tgodzik** [comment]
> > We could try updating to scalameta SNAPSHOT first next time to figure out if anything needs to be fixed still. We wouldn't need to do a rerelease then.
> 
> 1. where do we get a scalameta snapshot?

I usually check the last release job output for the version https://github.com/scalameta/scalameta/actions/workflows/release.yml

It should also be available in sonatype (I think, but I would need to search for the link)

> 2. should we somehow include testing of scalafmt before merging scalameta commits? a bit drastic but it looks like scalafmt has more unit tests (and out of more than 3.5k tests, only two failed, so...)

I think testing manually before the release should really be enough. We already test a number of Scala 2 and Scala 3 sources, so anything big should pop up in the PRs. I usually do it just in case before the release.

**Comment by kitbellew** [comment]
@tgodzik found a published recent snapshot, build passes. now we need to wait until 4.4.26 is released.

**Comment by tgodzik** [comment]
I can release it tomorrow!

**Comment by tgodzik** [comment]
new release is on it's way! I made a mistake and released `2.2.26` instead of `4.4.26`, but it should be republished soon:
https://github.com/scalameta/scalameta/actions/runs/1102300362

**Comment by tgodzik** [comment]
The release is out, it should also close https://github.com/scalameta/scalafmt/issues/2640

**Comment by kitbellew** [comment]
@tgodzik PTAL

**Review by tgodzik — APPROVED** [review]
LGTM!

**Pull request merged**
