### PR TITLE
Relative config path option

### PR DESCRIPTION
**Pull request by vovapolu**
This PR adds new setting to configure relative path to scalafmt config.

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you for this contribution! My apologies, seems I messed up the git history. I did not intend to close your PR. I was trying to push a commit to your PR merging with the changes in #1007 The commit was here https://github.com/scalameta/scalafmt/commit/e3862983442fae653141676652bdb1425e4ca685

Everything looks great, just tested locally and it works nicely 😄

**Comment by olafurpg** [comment]
Your commit is now merged into master https://github.com/scalameta/scalafmt/commit/182d9be71ed78754ebc379a13daecd4a156c68dc I have no idea how to show this PR as merged however :/ So sorry!

**Comment by olafurpg** [comment]
I just published a version of the plugin on current master to the "nightly" channel of the plugin https://plugins.jetbrains.com/plugin/8236-scalafmt can you please double-check everything is OK before we publish it to the stable branch?

**Comment by vovapolu** [comment]
Thanks :) Nightly build works great.

**Comment by olafurpg** [comment]
1.2.0 out with this change :)

**Pull request closed without merging**
