### PR TITLE
Example for new sbt plugin

### PR DESCRIPTION
**Pull request by vovapolu**
Fixes https://github.com/scalameta/scalafmt/issues/1127

### CODE REVIEW

**Comment by vovapolu** [comment]
Oops, I've created new branch in the repo... I will delete it after.

**Comment by yawaramin** [comment]
I'm getting:

```
C:\Users\yquadiramin\Documents\src\transactions-accounts\build.sbt:107: error: not found: value scalafmtConfigSettings
inConfig(IntegrationTest)(scalafmtConfigSettings)
                          ^
[error] Type error in expression
```

Am I missing something?

**Comment by sourcekick** [comment]
How does activation of scalafmt in `it` scope work in scalafmt 2?

**Comment by sourcekick** [comment]
Okay, the docs still state
`inConfig(IntegrationTest)(org.scalafmt.sbt.ScalafmtPlugin.scalafmtConfigSettings)`

**Pull request merged**
