### PR TITLE
Style the page using the colors from the scalameta logo

### PR DESCRIPTION
**Pull request by mads-hartmann**
If merged the site will look like this:

screen shot 2018-04-22 at 19 39 34
screen shot 2018-04-22 at 19 40 01

### CODE REVIEW

**Comment by olafurpg** [comment]
Whoah 😍 

I love the new code listings, very fresh 👍  Overall, big LGTM.

Only one comment, the bright red color in the sidebar is a bit alarming. I took a stab at making it sligtly darker with
```css
ul.menu-item-list {
    background: #bb3e43;
    border-right: 2px solid #af2442;
}
```

screen shot 2018-04-22 at 20 24 50

It's a bit more bland, not as splashy, but lighter on the eye. I'm not sold yet, any suggestions?

**Comment by mads-hartmann** [comment]
I’m happy you like it. I’ll throw togehter a few suggestions tomorrow. I have a soft spot for alarming colors but i’ll try to tone it down a bit 😅

**Comment by olafurpg** [comment]
BTW, I've been thinking of moving the site to something markdown + tut based. I recently learned to use tut passthrough to replace the nice programmatic capabilities of scalatex.

If you are interested, I would love some help. We are exploring how to setup a new site for Metals in https://github.com/scalameta/metals/pull/294 Once we have something good, I would like to use the same setup for http://scalameta.org/ and http://scalameta.org/tutorial

I've been meaning for a while to write detailed docs on parsers/printers/traversers/semanticdb but always get stuck on the website.

**Comment by mads-hartmann** [comment]
Sure thing, I’d be happy to help. I’ll take a look later 👍🏻

**Comment by olafurpg** [comment]
Re: colors

I like bright colors! My biggest gripe is lack of contrast between background and text, I find it difficult to read white font on bright red background.

**Comment by mads-hartmann** [comment]
@olafurpg Here are some color combinations I've used on my blog. Does any of these combinations strike your fancy?

- [Redish](http://mads-hartmann.com/2018/03/24/famlydev-proxy.html)
- [Purpleish](http://mads-hartmann.com/2017/08/06/writing-zsh-completion-scripts.html)
- [Don't know what to call this](http://mads-hartmann.com/2017/08/02/why-i-love-dotfiles.html)
- [Yellow](http://mads-hartmann.com/ocaml/2015/01/05/gadt-ocaml.html)

I totally agree that the contract right now is off 👍

**Comment by olafurpg** [comment]
Nice blog! I like the dotfiles colors, I've always been weak for purple 😊 The yellow and black is nice too.

Do you know any good template/static site generator for docs? I've tried hugo, gitbook, docusaurus, jekyll, [ornate](https://szeiger.github.io/ornate-doc/), [doxidize](https://steveklabnik.github.io/doxidize/quickstart.html), [sphinx](http://www.sphinx-doc.org/en/master/), read the docs, [mkdocs](http://www.mkdocs.org/) but struggled to get

- github-flavored markdown 
- always accessible sidebar to jump between pages
- always accessible TOC for open page
- search (either generated in site or algolia is fine too)
- "edit on github" links
- anchor refs to headers for easy "click and share link to section"
- template variable splicing to insert dynamic strings like project version (for copy-paste friendly installation instructions).
- ability to inline subsets of external files, like `@hl.ref` in http://www.lihaoyi.com/Scalatex/#Highlighter (ideally with link to original file on github)
- fast edit/preview feedback loop
- nice landing page, something like https://docusaurus.io/ or https://bucklescript.github.io/
- (optional) single page pdf generation

I can configure tut integration and publish to ghpages with mostly anything. My failure is a bigger sign of my experience with html/css than lack of functionality in those site generators 😅

**Comment by olafurpg** [comment]
Moved this discussion to an issue #1146

I'm sorry I didn't mean to block this PR, which is already a great improvement as it is. I would be happy to merge it with a less dramatic change to the sidebar colors, the code listings are very beautiful.

**Comment by mads-hartmann** [comment]
Thanks! I'll try a few color options later but and then I think we should merge this :) I'll join the other discussion and once we've settled on a tool I'd be happy to help port this one

**Comment by mads-hartmann** [comment]
@olafurpg How do you feel about this?
screen shot 2018-04-23 at 18 11 13

**Comment by olafurpg** [comment]
That looks nice! Can you push so I can test it locally?

**Comment by mads-hartmann** [comment]
I tried a couple of other colors but didn't quite like any of them :)

**Comment by olafurpg** [comment]
Just tried it locally and ❤️ 

The bright red color for select section was still a bit alarming at first, but I got used to it quickly and I like now :)

Any thoughts @pjrt ?

**Comment by olafurpg** [comment]
btw, I don't know if this can be fixed in css or not, but it has always bugged me that clicking on sections cuts the header at the top
screen shot 2018-04-23 at 19 06 56
Top of "Related" is hidden by top of window. Is it possible to add some padding/margin to let the header breathe?

**Comment by pjrt** [comment]
Are we going for red-ish because of Scala's logo? That makes sense, though is that the Scala red? Something looks different on it. 

But I am by no means a designer so don't take my opinion too strongly. I do agree with the overall change to red-like-things.

**Comment by olafurpg** [comment]
The colors match the scalameta logo from http://scalameta.org/

It's not intended to be the scala red color. Sounds good, let's do it 💪

**Comment by olafurpg** [comment]
IT'S ALIVE http://scalameta.org/scalafmt/

**Pull request merged**
