### PR TITLE
Migrate to sbt 1.0.0-M5 for sbt-scalafmt.

### PR DESCRIPTION
**Pull request by olafurpg**
- Remove sbt 0.13 plugin. It is not worth the maintenance cost.
  Users who want to stay on sbt 0.13 and want to use latest scalafmt
  versions can copy the single-file plugin
  https://github.com/scalameta/scalafmt/blob/master/scalafmtSbt/src/main/scala/org/scalafmt/sbt/ScalafmtPlugin.scala
  and replace ScalafmtBootrap.main with
  ```scala
  val Right(scalafmt) = ScalafmtBootrap.fromVersion("<latest scalafmt version>")
  scalafmt.main(args)
  ```
- scripted tests are done with a dummy scalafmtSbtTest project because
  I couldn't figure out how to run scripted tests on the sbt 1.0 plugin
  because the scalafmt build is still on 0.13.15

### CODE REVIEW

**Comment by sjrd** [comment]
That's a harsh move. Very few people can afford to migrate to sbt 1 as long as it's not a final release. I also don't understand the maintenance cost argument: the last commit that touched the sbt plugin is dated from December.

I understand the good feeling that removing code provides, but I believe it is way too early for this move.

**Comment by olafurpg** [comment]
> maintenance

See 
https://github.com/scalameta/scalafmt/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Asbt%20
and
https://github.com/scalameta/scalafmt/commits/master/bootstrap/src/main/scala/org/scalafmt/bootstrap/Bootstrap.scala
All of those issues, of which some are still open, are related to hacks around the 2.10 requirement in sbt 0.13.

Those who are stuck on 0.13 can continue to use future scalafmt versions by staying on sbt-scalafmt 0.6.6 and writing this (untested) command

```scala
commands += Command.args("scalafmt") {
  case (state, args) =>
    val Right(scalafmt) org.scalafmt.bootstrap.ScalafmtBootstrap.fromVersion("<latest version>")
    scalafmt.main("--non-interactive" +: args.toArray)
    state
}
```
 
I'll add a section in the docs explaining this workaround.

I've tried really hard and put a lot of hours into making sbt-scalafmt work on 0.13. When I called for help in https://github.com/scalameta/scalafmt/issues/597 no-one stepped up to help. Given that I personally don't even use the sbt plugin, my patience for supporting sbt 0.13 is running out now that sbt 1.0 is on the way.

**Comment by olafurpg** [comment]
I've added an example repo on how to use the latest scalafmt versions with sbt 0.13 here: https://github.com/olafurpg/sbt-scalafmt-0.13/blob/master/build.sbt

I've updated this PR to add a "sbt 0.13" section in the docs explaining this workaround.

**Comment by olafurpg** [comment]
Given that sbt 0.13 users can continue to use the latest scalafmt version with scalafmt-bootstrap, see https://github.com/olafurpg/sbt-scalafmt-0.13, I'm gonna go ahead and merge this PR. I hope that this change motivates people to upgrade to sbt 1.0 as soon as possible.

PS. I think it's amazing that this new plugin for sbt 1.0 is only 22 lines of code. In fact, the build configuration needed to run the scripted tests contains code than the plugin implementation 😄

**Comment by olafurpg** [comment]
The appveyor setup has been broken for a while, it's unrelated to this PR.

**Pull request merged**
