### PR TITLE
Fix off-by-one error, #976.

### PR DESCRIPTION
**Pull request by olafurpg**
Interestingly, this had not been pointed out before.

### CODE REVIEW

**Comment by olafurpg** [comment]
Review @alexnixon

**Comment by olafurpg** [comment]
This change broke a bunch of tests, which relied on the old behavior, so I took a shortcut and moved the maxColumn setting to 79 for the test suite 😅

**Comment by olafurpg** [comment]
This is quite a big change, but I think it's the right thing to do.

**Comment by alexnixon** [comment]
With 0 knowledge of the codebase...LGTM! Thanks for jumping on this so quickly.

**Comment by olafurpg** [comment]
I added a test case @pjrt

**Pull request merged**
