### PR TITLE
Reorganise the documentation for configuration options

### PR DESCRIPTION
**Pull request by mads-hartmann**
I find the existing flat list to be a bit overwhelming so I tried to
group the relevant settings together a bit.

I realise the docs site might be rewritten in the near future but I
still find it valuable to explore how best to group the configuration
options.

### CODE REVIEW

**Comment by mads-hartmann** [comment]
The TOC looks like this after the reorganisation: 
screen shot 2018-04-25 at 21 24 55

**Comment by mads-hartmann** [comment]
This is what nodes styled using `@warning` looks like:

screen shot 2018-04-25 at 23 01 37

**Comment by mads-hartmann** [comment]
@olafurpg I pushed a commit that introduces a `Most Poplar` section right after `style` - how do you feel about that solution?

As for moving project.git

**Comment by mads-hartmann** [comment]
@olafurpg This is ready for a new review ☺️

**Comment by olafurpg** [comment]
btw, vertical multiline still looks weird

screen shot 2018-04-28 at 13 47 54

I'm wondering if it better to show the examples vertically instead of horizontally?

**Comment by mads-hartmann** [comment]
@olafurpg Is that from this branch or master after it was merged? I think this branch was behind master :)

**Comment by olafurpg** [comment]
Right I was confused because I thought it was already fixed, didn't think it was only in your branch :)

**Pull request merged**
