### PR TITLE
Router: remove unnecessary splits cache, used once

### PR DESCRIPTION
**Pull request by kitbellew**
Also rename so it doesn't convey the "memo" meaning anymore.

### CODE REVIEW

**Comment by kitbellew** [comment]
@olafurpg @poslegm PTAL

**Comment by kitbellew** [comment]
@poslegm @olafurpg i need help, please!

i tagged the last merged commit with v2.5.0-rc1 but the build failed:
https://github.com/scalameta/scalafmt/actions/runs/78916320

looks like it's the first ever release through github actions, and it fails in `git fetch --tags`:
```
* [new tag]           v2.4.2            -> v2.4.2
 ! [rejected]          v2.5.0-RC1        -> v2.5.0-RC1  (would clobber existing tag)
##[error]Process completed with exit code 1.
```
possibly because `v2.5.0-RC1` was currently checked out.

i have no idea how to fix this (don't know much about yaml, github actions or why we need to fetch tags). can you help, please?

**Comment by poslegm** [comment]
Releases are being made in Travis. Release of 2.5.0-RC1 is success: https://travis-ci.org/github/scalameta/scalafmt/builds/675288138

Failed job is a just usual CI on master push.

**Comment by poslegm** [comment]
> why we need to fetch tags

scalafmt [needs to know](https://github.com/scalameta/scalafmt/blob/5f8ac946afb73d1e42d038e269d7cfb1be985b0b/scalafmt-dynamic/src/main/scala/org/scalafmt/dynamic/ScalafmtDynamicDownloader.scala) it's own version. Version comes from https://github.com/dwijnand/sbt-dynver and it uses git tags.

**Comment by kitbellew** [comment]
> Releases are being made in Travis. Release of 2.5.0-RC1 is success: https://travis-ci.org/github/scalameta/scalafmt/builds/675288138
> 
> Failed job is a just usual CI on master push.

ah, nice! thank you. will it automatically propagate to maven and other package repositories? should i ask people to test it now?

**Comment by poslegm** [comment]
There is no need to run test CI on tags push. I will disable it later.

> will it automatically propagate to maven and other package repositories?

Yes

>should i ask people to test it now?

No.

Publishing process to Maven Central may take hours. We need to wait new version available [here](https://search.maven.org/artifact/org.scalameta/scalafmt-core_2.13)

**Pull request merged**
