### PR TITLE
Add tests for #2480

### PR DESCRIPTION
**Pull request by tgodzik**
Fixes https://github.com/scalameta/scalafmt/issues/2480

### CODE REVIEW

**Review by kitbellew — APPROVED** [review]

**Comment by kitbellew** [comment]
@tgodzik this was the last scala3-related issue. want to try for rc3?

**Comment by tgodzik** [comment]
I found another issue in the parser so maybe after that one is merged? Though it's a minor thing which we can add in the final version and in the meantime test out for any other issues.

**Comment by kitbellew** [comment]
let's fix the parser.

**Comment by tgodzik** [comment]
Fixing it here https://github.com/scalameta/scalameta/pull/2341 and I also want to check another issue reported to me internally.

**Pull request merged**
