### PR TITLE
ScalafmtRunner: remove old dialects, add 212s3

### PR DESCRIPTION
**Pull request by kitbellew**

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
LGTM

**Review by tgodzik — CHANGES_REQUESTED** [review]
Actually, some tests are failing. Went too trigger happy here 😅

**Comment by kitbellew** [comment]
> Actually, some tests are failing. Went too trigger happy here 😅

me, too. fixed.

**Review by tgodzik — APPROVED** [review]
Now, truly LGTM!

**Pull request merged**
