### PR TITLE
Fix links in documents

### PR DESCRIPTION
**Pull request by YoshinoriN**
Hello :)
I fixed some broken or old links in documents.

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you for this contribution! I believe these changes are already covered by #1397

**Comment by YoshinoriN** [comment]
Oops... it's so sorry.
Ok, I closed this PR :)

**Comment by er1c** [comment]
a couple from the contributing/readmes aren't included

**Comment by YoshinoriN** [comment]
Thanks.

So, should I re-open PR & rebase after merged #1397 or ask to @ches to include contributing/readmes changes? Which is better?

**Comment by ches** [comment]
I can cherry pick this commit into my PR if that makes everyone’s life easier, I’ll finish the changes in a bit…

**Comment by YoshinoriN** [comment]
@ches 
Thank you very much. I am grateful for your support.

**Pull request closed without merging**
