### PR TITLE
Add section on align.openParenDefnSite

### PR DESCRIPTION
**Pull request by lorandszakacs**
Hopefully this is all that is needed 😅

### CODE REVIEW

**Comment by olafurpg** [comment]
@lorandszakacs I just noticed the new section is top-level

screen shot 2018-02-07 at 11 32 14


Could you maybe move it under the  "Configuration part"?

**Comment by olafurpg** [comment]
@lorandszakacs I just noticed the new section is top-level

screen shot 2018-02-07 at 11 32 14


Could you maybe move it under the  "Configuration part"?

**Comment by lorandszakacs** [comment]
@olafurpg will do asap. Sometime in the next few hours. My bad.

**Comment by olafurpg** [comment]
no worries, I didn't notice myself

**Comment by lorandszakacs** [comment]
@olafurpg sorry for the delay. Opened a fix PR:
https://github.com/scalameta/scalafmt/pull/1108

**Pull request merged**
